Repository Ivy-Interactive/Ivy-Framework, pull requests merged in 2025-07, with the labels that each got.

#79 (boolinput): rename not implemented into N/A
  Ivy.Samples/Apps/Widgets/Inputs/BoolInputApp.cs
Labels: Ivy-Samples

#80 (code-input) chore: treat c# as c++
  frontend/package-lock.json
  frontend/package.json
  frontend/src/widgets/inputs/CodeInputWidget.tsx
Labels: Ivy-Samples

#86 (forms): no scrollbar
  frontend/src/components/ui/dialog.tsx
  frontend/src/widgets/dialogs/DialogBodyWidget.tsx
Labels: bug, Ivy-Samples

#129 Select Input
  Ivy.Docs/Docs/02_Widgets/02_Inputs/Bool.md
  Ivy.Docs/Docs/02_Widgets/02_Inputs/Feedback.md
  Ivy.Docs/Docs/02_Widgets/02_Inputs/Select.md
Labels: documentation

#161 (docs): installation rework
  Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/02_Installation.md
Labels: documentation

#162 feat: better grid with supported types
  Ivy.Docs/Helpers/TypeUtils.cs
  Ivy.Docs/Helpers/WidgetDocsView.cs
  Ivy/Widgets/Inputs/FeedbackInput.cs
Labels: documentation

#122 Draft: feat: get path for link cross-platform
  Ivy.Docs.Tools/Utils.cs
  Ivy.Docs/Ivy.Docs.csproj
Labels: bug

#120 (tests): bool-input variants tests
  Ivy.Samples/Apps/Widgets/Inputs/BoolInputApp.cs
  frontend/e2e/bool-input.spec.ts
  frontend/src/components/ui/toggle.tsx
Labels: Ivy-Samples

#202 feat: enhance markdown component documentation with comprehensive examples
  Ivy.Docs/Docs/02_Widgets/03_Primitives/Markdown.md
Labels: documentation

#173 feat: file input size and format features
  Ivy.Samples/Apps/Widgets/Inputs/FileInputApp.cs
  Ivy/Widgets/Inputs/FileInput.cs
  frontend/src/widgets/inputs/FileInputWidget.tsx
Labels: enhancement, Ivy-Samples

#199 feat: implement comprehensive Colors.md documentation
  Ivy.Docs/Docs/03_ApiReference/IvyShared/Colors.md
  Ivy/Tables/TableBuilder.cs
  Ivy/Utils.cs
Labels: documentation

#200 docs: enhance HTML widget documentation with comprehensive examples
  Ivy.Docs.Tools/LinkConverter.cs
  Ivy.Docs/Docs/02_Widgets/03_Primitives/Html.md
  Ivy.Docs/Helpers/WidgetDocsView.cs
Labels: documentation

#223 Feat/pie chart examples
  Ivy.Samples/Apps/Widgets/Charts/PieChartApp.cs
  Ivy/Charts/PieChartView.cs
Labels: Ivy-Samples

#224 feat: line chart view expansion
  Ivy.Samples/Apps/Widgets/Charts/LineChartApp.cs
  Ivy/Charts/LineChartView.cs
Labels: Ivy-Samples

#221 feat: be checks for filetype and count
  Ivy.Samples/Apps/Widgets/Inputs/FileInputApp.cs
  Ivy.Test/FileInputValidationTests.cs
  Ivy/Widgets/Inputs/FileInput.cs
  Ivy/Widgets/Inputs/FileInputValidation.cs
Labels: Ivy-Samples

#237 feat: theming and cursor events
  Ivy.Docs/Docs/02_Widgets/03_Primitives/Html.md
  frontend/src/components/EmojiRating.tsx
  frontend/src/components/NumberInput.tsx
  frontend/src/components/StarRating.tsx
  frontend/src/components/ThumbsRating.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/radio-group.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/slider.tsx
  frontend/src/components/ui/toggle.tsx
  frontend/src/widgets/blades/BladeWidget.tsx
  frontend/src/widgets/inputs/AsyncSelectInputWidget.tsx
  frontend/src/widgets/inputs/CodeInputWidget.tsx
  frontend/src/widgets/inputs/ColorInputWidget.tsx
  frontend/src/widgets/inputs/DateRangeInputWidget.tsx
  frontend/src/widgets/inputs/DateTimeInputWidget.tsx
  frontend/src/widgets/inputs/FileInputWidget.tsx
  frontend/src/widgets/inputs/SelectInputWidget.tsx
  frontend/src/widgets/inputs/TextInputWidget.tsx
  frontend/src/widgets/internal/DbmlCanvasWidget.tsx
  frontend/src/widgets/layouts/TabsLayoutWidget.tsx
  frontend/src/widgets/lists/ListItemWidget.tsx
  frontend/src/widgets/lists/ListWidget.tsx
  frontend/src/widgets/primitives/HtmlWidget.tsx
  frontend/src/widgets/tables/TableCellWidget.tsx
  frontend/src/widgets/tables/TableRowWidget.tsx
Labels: enhancement

#259 feat: expandable remove extra padding
  frontend/src/widgets/ExpandableWidget.tsx
Labels: Ivy-Samples

#275 Add animations
  frontend/src/components/ui/sheet.tsx
  frontend/src/components/ui/toast.tsx
  frontend/src/index.css
  frontend/src/widgets/SheetWidget.tsx
  frontend/src/widgets/dialogs/DialogWidget.tsx
  frontend/src/widgets/layouts/FooterLayoutWidget.tsx
Labels: Ivy-Samples

#292 improve stylings for select list and checkboxes
  Ivy.Samples/Apps/Widgets/Inputs/SelectInputApp.cs
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/multiselect.tsx
  frontend/src/widgets/inputs/SelectInputWidget.tsx
Labels: Ivy-Samples

#293 (terminal): only add > to commands, not outputs
  Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/02_Installation.md
  Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/03_Basics.md
  Ivy.Docs/Docs/01_Onboarding/01_GettingStarted/05_TodoTutorial.md
  frontend/src/widgets/internal/TerminalWidget.tsx
Labels: bug

#297 typography: more consistent results for html, md and text widgets
  Ivy.Docs/Docs/02_Widgets/04_Layouts/GridLayout.md
  Ivy.Docs/Helpers/EnumValuesView.cs
  Ivy.Docs/Helpers/WidgetDocsView.cs
  frontend/src/components/HtmlRenderer.tsx
  frontend/src/components/MarkdownRenderer.tsx
  frontend/src/lib/textBlockClassMap.ts
  frontend/src/widgets/primitives/ArticleWidget.tsx
Labels: Ivy-Samples

#306 bugfix: blade's width modifies when we open another blade
  frontend/src/widgets/blades/BladeWidget.tsx
Labels: bug
